/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#ifdef _MSC_VER
#pragma optimize("", off)
#elif defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize ("O0")
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND_POUNDUSER_COLON = 1,
  anon_sym_POUND_POUNDSYSTEM_COLON = 2,
  anon_sym_POUND_POUNDASSISTANT_COLON = 3,
  anon_sym_POUND_POUNDTHINKING_COLON = 4,
  anon_sym_POUND_POUNDTOOLUSE_COLON = 5,
  anon_sym_POUND_POUNDTOOLRESULT_COLON = 6,
  anon_sym_POUND_POUNDSERVERTOOLUSE_COLON = 7,
  anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON = 8,
  anon_sym_POUND_POUNDCITATIONS_COLON = 9,
  aux_sym_content_line_token1 = 10,
  anon_sym_Name_COLON = 11,
  aux_sym_tool_name_line_token1 = 12,
  aux_sym_tool_name_line_token2 = 13,
  anon_sym_ID_COLON = 14,
  anon_sym_POUND_POUND_POUND = 15,
  anon_sym_LTtool_DOT = 16,
  aux_sym_tool_tag_token1 = 17,
  anon_sym_GT = 18,
  anon_sym_LT_SLASHtool_DOT = 19,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 20,
  aux_sym_code_fence_token1 = 21,
  anon_sym_LT_BANG_DASH_DASH = 22,
  anon_sym_DASH_DASH_GT = 23,
  anon_sym_LTinclude = 24,
  anon_sym_code = 25,
  aux_sym_include_tag_token1 = 26,
  anon_sym_LT_SLASHinclude_GT = 27,
  anon_sym_LTsafe_DASHshell_DASHcommands_GT = 28,
  anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT = 29,
  anon_sym_LTcite_GT = 30,
  anon_sym_LT_SLASHcite_GT = 31,
  sym_text_content = 32,
  sym_document = 33,
  sym_section_header = 34,
  sym_content_line = 35,
  sym_empty_line = 36,
  sym_tool_name_line = 37,
  sym_tool_id_line = 38,
  sym_tool_parameter_header = 39,
  sym_tool_tag = 40,
  sym_code_fence = 41,
  sym_html_comment_marker = 42,
  sym_include_tag = 43,
  sym_safe_shell_tag = 44,
  sym_cite_tag = 45,
  aux_sym_document_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND_POUNDUSER_COLON] = "## USER:",
  [anon_sym_POUND_POUNDSYSTEM_COLON] = "## SYSTEM:",
  [anon_sym_POUND_POUNDASSISTANT_COLON] = "## ASSISTANT:",
  [anon_sym_POUND_POUNDTHINKING_COLON] = "## THINKING:",
  [anon_sym_POUND_POUNDTOOLUSE_COLON] = "## TOOL USE:",
  [anon_sym_POUND_POUNDTOOLRESULT_COLON] = "## TOOL RESULT:",
  [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = "## SERVER TOOL USE:",
  [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = "## SERVER TOOL RESULT:",
  [anon_sym_POUND_POUNDCITATIONS_COLON] = "## CITATIONS:",
  [aux_sym_content_line_token1] = "content_line_token1",
  [anon_sym_Name_COLON] = "Name:",
  [aux_sym_tool_name_line_token1] = "tool_name_line_token1",
  [aux_sym_tool_name_line_token2] = "tool_name_line_token2",
  [anon_sym_ID_COLON] = "ID:",
  [anon_sym_POUND_POUND_POUND] = "###",
  [anon_sym_LTtool_DOT] = "<tool.",
  [aux_sym_tool_tag_token1] = "tool_tag_token1",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASHtool_DOT] = "</tool.",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [aux_sym_code_fence_token1] = "code_fence_token1",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [anon_sym_LTinclude] = "<include",
  [anon_sym_code] = "code",
  [aux_sym_include_tag_token1] = "include_tag_token1",
  [anon_sym_LT_SLASHinclude_GT] = "</include>",
  [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = "<safe-shell-commands>",
  [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = "</safe-shell-commands>",
  [anon_sym_LTcite_GT] = "<cite>",
  [anon_sym_LT_SLASHcite_GT] = "</cite>",
  [sym_text_content] = "text_content",
  [sym_document] = "document",
  [sym_section_header] = "section_header",
  [sym_content_line] = "content_line",
  [sym_empty_line] = "empty_line",
  [sym_tool_name_line] = "tool_name_line",
  [sym_tool_id_line] = "tool_id_line",
  [sym_tool_parameter_header] = "tool_parameter_header",
  [sym_tool_tag] = "tool_tag",
  [sym_code_fence] = "code_fence",
  [sym_html_comment_marker] = "html_comment_marker",
  [sym_include_tag] = "include_tag",
  [sym_safe_shell_tag] = "safe_shell_tag",
  [sym_cite_tag] = "cite_tag",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND_POUNDUSER_COLON] = anon_sym_POUND_POUNDUSER_COLON,
  [anon_sym_POUND_POUNDSYSTEM_COLON] = anon_sym_POUND_POUNDSYSTEM_COLON,
  [anon_sym_POUND_POUNDASSISTANT_COLON] = anon_sym_POUND_POUNDASSISTANT_COLON,
  [anon_sym_POUND_POUNDTHINKING_COLON] = anon_sym_POUND_POUNDTHINKING_COLON,
  [anon_sym_POUND_POUNDTOOLUSE_COLON] = anon_sym_POUND_POUNDTOOLUSE_COLON,
  [anon_sym_POUND_POUNDTOOLRESULT_COLON] = anon_sym_POUND_POUNDTOOLRESULT_COLON,
  [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = anon_sym_POUND_POUNDSERVERTOOLUSE_COLON,
  [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON,
  [anon_sym_POUND_POUNDCITATIONS_COLON] = anon_sym_POUND_POUNDCITATIONS_COLON,
  [aux_sym_content_line_token1] = aux_sym_content_line_token1,
  [anon_sym_Name_COLON] = anon_sym_Name_COLON,
  [aux_sym_tool_name_line_token1] = aux_sym_tool_name_line_token1,
  [aux_sym_tool_name_line_token2] = aux_sym_tool_name_line_token2,
  [anon_sym_ID_COLON] = anon_sym_ID_COLON,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [anon_sym_LTtool_DOT] = anon_sym_LTtool_DOT,
  [aux_sym_tool_tag_token1] = aux_sym_tool_tag_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASHtool_DOT] = anon_sym_LT_SLASHtool_DOT,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [aux_sym_code_fence_token1] = aux_sym_code_fence_token1,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [anon_sym_LTinclude] = anon_sym_LTinclude,
  [anon_sym_code] = anon_sym_code,
  [aux_sym_include_tag_token1] = aux_sym_include_tag_token1,
  [anon_sym_LT_SLASHinclude_GT] = anon_sym_LT_SLASHinclude_GT,
  [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = anon_sym_LTsafe_DASHshell_DASHcommands_GT,
  [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT,
  [anon_sym_LTcite_GT] = anon_sym_LTcite_GT,
  [anon_sym_LT_SLASHcite_GT] = anon_sym_LT_SLASHcite_GT,
  [sym_text_content] = sym_text_content,
  [sym_document] = sym_document,
  [sym_section_header] = sym_section_header,
  [sym_content_line] = sym_content_line,
  [sym_empty_line] = sym_empty_line,
  [sym_tool_name_line] = sym_tool_name_line,
  [sym_tool_id_line] = sym_tool_id_line,
  [sym_tool_parameter_header] = sym_tool_parameter_header,
  [sym_tool_tag] = sym_tool_tag,
  [sym_code_fence] = sym_code_fence,
  [sym_html_comment_marker] = sym_html_comment_marker,
  [sym_include_tag] = sym_include_tag,
  [sym_safe_shell_tag] = sym_safe_shell_tag,
  [sym_cite_tag] = sym_cite_tag,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND_POUNDUSER_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDSYSTEM_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDASSISTANT_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDTHINKING_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDTOOLUSE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDTOOLRESULT_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDCITATIONS_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_content_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Name_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tool_name_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tool_name_line_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_ID_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTtool_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tool_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHtool_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_fence_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_code] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_include_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_SLASHinclude_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTcite_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHcite_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_name_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_id_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_parameter_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_code_fence] = {
    .visible = true,
    .named = true,
  },
  [sym_html_comment_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_include_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_safe_shell_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_cite_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(162);
      ADVANCE_MAP(
        '\n', 181,
        '#', 7,
        '-', 8,
        '<', 6,
        '>', 193,
        'I', 37,
        'N', 95,
        '`', 94,
        'c', 143,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '>') ADVANCE(193);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(184);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(34);
      if (lookahead == '#') ADVANCE(188);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(70);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(85);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(71);
      END_STATE();
    case 6:
      if (lookahead == '!') ADVANCE(12);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == 'c') ADVANCE(124);
      if (lookahead == 'i') ADVANCE(139);
      if (lookahead == 's') ADVANCE(96);
      if (lookahead == 't') ADVANCE(146);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(2);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(200);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(150);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(101);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(104);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(153);
      END_STATE();
    case 15:
      if (lookahead == '.') ADVANCE(190);
      END_STATE();
    case 16:
      if (lookahead == '.') ADVANCE(194);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(186);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(182);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(163);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(165);
      END_STATE();
    case 21:
      if (lookahead == ':') ADVANCE(169);
      END_STATE();
    case 22:
      if (lookahead == ':') ADVANCE(171);
      END_STATE();
    case 23:
      if (lookahead == ':') ADVANCE(167);
      END_STATE();
    case 24:
      if (lookahead == ':') ADVANCE(179);
      END_STATE();
    case 25:
      if (lookahead == ':') ADVANCE(173);
      END_STATE();
    case 26:
      if (lookahead == ':') ADVANCE(175);
      END_STATE();
    case 27:
      if (lookahead == ':') ADVANCE(177);
      END_STATE();
    case 28:
      if (lookahead == '>') ADVANCE(202);
      END_STATE();
    case 29:
      if (lookahead == '>') ADVANCE(214);
      END_STATE();
    case 30:
      if (lookahead == '>') ADVANCE(216);
      END_STATE();
    case 31:
      if (lookahead == '>') ADVANCE(209);
      END_STATE();
    case 32:
      if (lookahead == '>') ADVANCE(210);
      END_STATE();
    case 33:
      if (lookahead == '>') ADVANCE(212);
      END_STATE();
    case 34:
      if (lookahead == 'A') ADVANCE(75);
      if (lookahead == 'C') ADVANCE(48);
      if (lookahead == 'S') ADVANCE(38);
      if (lookahead == 'T') ADVANCE(47);
      if (lookahead == 'U') ADVANCE(72);
      END_STATE();
    case 35:
      if (lookahead == 'A') ADVANCE(86);
      END_STATE();
    case 36:
      if (lookahead == 'A') ADVANCE(61);
      END_STATE();
    case 37:
      if (lookahead == 'D') ADVANCE(17);
      END_STATE();
    case 38:
      if (lookahead == 'E') ADVANCE(67);
      if (lookahead == 'Y') ADVANCE(74);
      END_STATE();
    case 39:
      if (lookahead == 'E') ADVANCE(58);
      END_STATE();
    case 40:
      if (lookahead == 'E') ADVANCE(69);
      END_STATE();
    case 41:
      if (lookahead == 'E') ADVANCE(68);
      END_STATE();
    case 42:
      if (lookahead == 'E') ADVANCE(22);
      END_STATE();
    case 43:
      if (lookahead == 'E') ADVANCE(73);
      END_STATE();
    case 44:
      if (lookahead == 'E') ADVANCE(26);
      END_STATE();
    case 45:
      if (lookahead == 'E') ADVANCE(81);
      END_STATE();
    case 46:
      if (lookahead == 'G') ADVANCE(21);
      END_STATE();
    case 47:
      if (lookahead == 'H') ADVANCE(49);
      if (lookahead == 'O') ADVANCE(63);
      END_STATE();
    case 48:
      if (lookahead == 'I') ADVANCE(82);
      END_STATE();
    case 49:
      if (lookahead == 'I') ADVANCE(59);
      END_STATE();
    case 50:
      if (lookahead == 'I') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'I') ADVANCE(60);
      END_STATE();
    case 52:
      if (lookahead == 'I') ADVANCE(79);
      END_STATE();
    case 53:
      if (lookahead == 'K') ADVANCE(51);
      END_STATE();
    case 54:
      if (lookahead == 'L') ADVANCE(3);
      END_STATE();
    case 55:
      if (lookahead == 'L') ADVANCE(88);
      END_STATE();
    case 56:
      if (lookahead == 'L') ADVANCE(89);
      END_STATE();
    case 57:
      if (lookahead == 'L') ADVANCE(5);
      END_STATE();
    case 58:
      if (lookahead == 'M') ADVANCE(20);
      END_STATE();
    case 59:
      if (lookahead == 'N') ADVANCE(53);
      END_STATE();
    case 60:
      if (lookahead == 'N') ADVANCE(46);
      END_STATE();
    case 61:
      if (lookahead == 'N') ADVANCE(87);
      END_STATE();
    case 62:
      if (lookahead == 'N') ADVANCE(78);
      END_STATE();
    case 63:
      if (lookahead == 'O') ADVANCE(54);
      END_STATE();
    case 64:
      if (lookahead == 'O') ADVANCE(62);
      END_STATE();
    case 65:
      if (lookahead == 'O') ADVANCE(57);
      END_STATE();
    case 66:
      if (lookahead == 'O') ADVANCE(65);
      END_STATE();
    case 67:
      if (lookahead == 'R') ADVANCE(92);
      END_STATE();
    case 68:
      if (lookahead == 'R') ADVANCE(4);
      END_STATE();
    case 69:
      if (lookahead == 'R') ADVANCE(19);
      END_STATE();
    case 70:
      if (lookahead == 'R') ADVANCE(43);
      if (lookahead == 'U') ADVANCE(77);
      END_STATE();
    case 71:
      if (lookahead == 'R') ADVANCE(45);
      if (lookahead == 'U') ADVANCE(80);
      END_STATE();
    case 72:
      if (lookahead == 'S') ADVANCE(40);
      END_STATE();
    case 73:
      if (lookahead == 'S') ADVANCE(90);
      END_STATE();
    case 74:
      if (lookahead == 'S') ADVANCE(83);
      END_STATE();
    case 75:
      if (lookahead == 'S') ADVANCE(76);
      END_STATE();
    case 76:
      if (lookahead == 'S') ADVANCE(52);
      END_STATE();
    case 77:
      if (lookahead == 'S') ADVANCE(42);
      END_STATE();
    case 78:
      if (lookahead == 'S') ADVANCE(24);
      END_STATE();
    case 79:
      if (lookahead == 'S') ADVANCE(84);
      END_STATE();
    case 80:
      if (lookahead == 'S') ADVANCE(44);
      END_STATE();
    case 81:
      if (lookahead == 'S') ADVANCE(91);
      END_STATE();
    case 82:
      if (lookahead == 'T') ADVANCE(35);
      END_STATE();
    case 83:
      if (lookahead == 'T') ADVANCE(39);
      END_STATE();
    case 84:
      if (lookahead == 'T') ADVANCE(36);
      END_STATE();
    case 85:
      if (lookahead == 'T') ADVANCE(66);
      END_STATE();
    case 86:
      if (lookahead == 'T') ADVANCE(50);
      END_STATE();
    case 87:
      if (lookahead == 'T') ADVANCE(23);
      END_STATE();
    case 88:
      if (lookahead == 'T') ADVANCE(25);
      END_STATE();
    case 89:
      if (lookahead == 'T') ADVANCE(27);
      END_STATE();
    case 90:
      if (lookahead == 'U') ADVANCE(55);
      END_STATE();
    case 91:
      if (lookahead == 'U') ADVANCE(56);
      END_STATE();
    case 92:
      if (lookahead == 'V') ADVANCE(41);
      END_STATE();
    case 93:
      if (lookahead == '`') ADVANCE(196);
      END_STATE();
    case 94:
      if (lookahead == '`') ADVANCE(93);
      END_STATE();
    case 95:
      if (lookahead == 'a') ADVANCE(134);
      END_STATE();
    case 96:
      if (lookahead == 'a') ADVANCE(120);
      END_STATE();
    case 97:
      if (lookahead == 'a') ADVANCE(140);
      END_STATE();
    case 98:
      if (lookahead == 'a') ADVANCE(141);
      END_STATE();
    case 99:
      if (lookahead == 'a') ADVANCE(121);
      END_STATE();
    case 100:
      if (lookahead == 'c') ADVANCE(126);
      END_STATE();
    case 101:
      if (lookahead == 'c') ADVANCE(144);
      END_STATE();
    case 102:
      if (lookahead == 'c') ADVANCE(125);
      if (lookahead == 'i') ADVANCE(142);
      if (lookahead == 's') ADVANCE(99);
      if (lookahead == 't') ADVANCE(148);
      END_STATE();
    case 103:
      if (lookahead == 'c') ADVANCE(131);
      END_STATE();
    case 104:
      if (lookahead == 'c') ADVANCE(149);
      END_STATE();
    case 105:
      if (lookahead == 'd') ADVANCE(110);
      END_STATE();
    case 106:
      if (lookahead == 'd') ADVANCE(151);
      END_STATE();
    case 107:
      if (lookahead == 'd') ADVANCE(111);
      END_STATE();
    case 108:
      if (lookahead == 'd') ADVANCE(116);
      END_STATE();
    case 109:
      if (lookahead == 'd') ADVANCE(152);
      END_STATE();
    case 110:
      if (lookahead == 'e') ADVANCE(206);
      END_STATE();
    case 111:
      if (lookahead == 'e') ADVANCE(204);
      END_STATE();
    case 112:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 113:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 114:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 115:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 116:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 117:
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(133);
      END_STATE();
    case 119:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 120:
      if (lookahead == 'f') ADVANCE(115);
      END_STATE();
    case 121:
      if (lookahead == 'f') ADVANCE(119);
      END_STATE();
    case 122:
      if (lookahead == 'h') ADVANCE(117);
      END_STATE();
    case 123:
      if (lookahead == 'h') ADVANCE(118);
      END_STATE();
    case 124:
      if (lookahead == 'i') ADVANCE(154);
      END_STATE();
    case 125:
      if (lookahead == 'i') ADVANCE(155);
      END_STATE();
    case 126:
      if (lookahead == 'l') ADVANCE(156);
      END_STATE();
    case 127:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 128:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 129:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 130:
      if (lookahead == 'l') ADVANCE(129);
      END_STATE();
    case 131:
      if (lookahead == 'l') ADVANCE(157);
      END_STATE();
    case 132:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 133:
      if (lookahead == 'l') ADVANCE(132);
      END_STATE();
    case 134:
      if (lookahead == 'm') ADVANCE(113);
      END_STATE();
    case 135:
      if (lookahead == 'm') ADVANCE(97);
      END_STATE();
    case 136:
      if (lookahead == 'm') ADVANCE(135);
      END_STATE();
    case 137:
      if (lookahead == 'm') ADVANCE(98);
      END_STATE();
    case 138:
      if (lookahead == 'm') ADVANCE(137);
      END_STATE();
    case 139:
      if (lookahead == 'n') ADVANCE(100);
      END_STATE();
    case 140:
      if (lookahead == 'n') ADVANCE(106);
      END_STATE();
    case 141:
      if (lookahead == 'n') ADVANCE(109);
      END_STATE();
    case 142:
      if (lookahead == 'n') ADVANCE(103);
      END_STATE();
    case 143:
      if (lookahead == 'o') ADVANCE(105);
      END_STATE();
    case 144:
      if (lookahead == 'o') ADVANCE(136);
      END_STATE();
    case 145:
      if (lookahead == 'o') ADVANCE(127);
      END_STATE();
    case 146:
      if (lookahead == 'o') ADVANCE(145);
      END_STATE();
    case 147:
      if (lookahead == 'o') ADVANCE(128);
      END_STATE();
    case 148:
      if (lookahead == 'o') ADVANCE(147);
      END_STATE();
    case 149:
      if (lookahead == 'o') ADVANCE(138);
      END_STATE();
    case 150:
      if (lookahead == 's') ADVANCE(122);
      END_STATE();
    case 151:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 152:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 153:
      if (lookahead == 's') ADVANCE(123);
      END_STATE();
    case 154:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 155:
      if (lookahead == 't') ADVANCE(114);
      END_STATE();
    case 156:
      if (lookahead == 'u') ADVANCE(107);
      END_STATE();
    case 157:
      if (lookahead == 'u') ADVANCE(108);
      END_STATE();
    case 158:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(158);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(185);
      END_STATE();
    case 159:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(207);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '<') ADVANCE(208);
      END_STATE();
    case 160:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(160);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>') ADVANCE(192);
      END_STATE();
    case 161:
      if (eof) ADVANCE(162);
      ADVANCE_MAP(
        '\n', 181,
        '#', 224,
        '-', 225,
        '<', 222,
        'I', 253,
        'N', 311,
        '`', 310,
        '\t', 223,
        '\r', 223,
        ' ', 223,
      );
      if (lookahead != 0) ADVANCE(365);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDUSER_COLON);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDUSER_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDSYSTEM_COLON);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDSYSTEM_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDASSISTANT_COLON);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDASSISTANT_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDTHINKING_COLON);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDTHINKING_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDTOOLUSE_COLON);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDTOOLUSE_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDTOOLRESULT_COLON);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDTOOLRESULT_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDSERVERTOOLUSE_COLON);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDSERVERTOOLUSE_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDCITATIONS_COLON);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDCITATIONS_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(aux_sym_content_line_token1);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_Name_COLON);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(anon_sym_Name_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(aux_sym_tool_name_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(184);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(aux_sym_tool_name_line_token2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(185);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(anon_sym_ID_COLON);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_ID_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(anon_sym_LTtool_DOT);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(anon_sym_LTtool_DOT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(aux_sym_tool_tag_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '>') ADVANCE(192);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(anon_sym_LT_SLASHtool_DOT);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(anon_sym_LT_SLASHtool_DOT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(aux_sym_code_fence_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(198);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(199);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(aux_sym_code_fence_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(199);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_LTinclude);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_LTinclude);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_code);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(aux_sym_include_tag_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(207);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '<') ADVANCE(208);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(aux_sym_include_tag_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<') ADVANCE(208);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(anon_sym_LT_SLASHinclude_GT);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(anon_sym_LTsafe_DASHshell_DASHcommands_GT);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(anon_sym_LTsafe_DASHshell_DASHcommands_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(anon_sym_LTcite_GT);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(anon_sym_LTcite_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(anon_sym_LT_SLASHcite_GT);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(anon_sym_LT_SLASHcite_GT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ' ') ADVANCE(250);
      if (lookahead == '#') ADVANCE(189);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ' ') ADVANCE(286);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ' ') ADVANCE(301);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ' ') ADVANCE(287);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '!') ADVANCE(229);
      if (lookahead == '/') ADVANCE(318);
      if (lookahead == 'c') ADVANCE(335);
      if (lookahead == 'i') ADVANCE(349);
      if (lookahead == 's') ADVANCE(312);
      if (lookahead == 't') ADVANCE(352);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_text_content);
      ADVANCE_MAP(
        '#', 224,
        '-', 225,
        '<', 222,
        'I', 253,
        'N', 311,
        '`', 310,
        '\t', 223,
        '\r', 223,
        ' ', 223,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '#') ADVANCE(218);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-') ADVANCE(245);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-') ADVANCE(201);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-') ADVANCE(358);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-') ADVANCE(317);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-') ADVANCE(226);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-') ADVANCE(319);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-') ADVANCE(361);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '.') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '.') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == ':') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '>') ADVANCE(203);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '>') ADVANCE(215);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '>') ADVANCE(217);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '>') ADVANCE(211);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '>') ADVANCE(213);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'A') ADVANCE(291);
      if (lookahead == 'C') ADVANCE(264);
      if (lookahead == 'S') ADVANCE(254);
      if (lookahead == 'T') ADVANCE(263);
      if (lookahead == 'U') ADVANCE(288);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'A') ADVANCE(302);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'A') ADVANCE(277);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'D') ADVANCE(234);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'E') ADVANCE(283);
      if (lookahead == 'Y') ADVANCE(290);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'E') ADVANCE(274);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'E') ADVANCE(285);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'E') ADVANCE(284);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 258:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'E') ADVANCE(239);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 259:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'E') ADVANCE(289);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 260:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'E') ADVANCE(243);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 261:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'E') ADVANCE(297);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 262:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'G') ADVANCE(238);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 263:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'H') ADVANCE(265);
      if (lookahead == 'O') ADVANCE(279);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 264:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'I') ADVANCE(298);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 265:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'I') ADVANCE(275);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 266:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'I') ADVANCE(280);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 267:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'I') ADVANCE(276);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 268:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'I') ADVANCE(295);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'K') ADVANCE(267);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'L') ADVANCE(219);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 271:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'L') ADVANCE(304);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 272:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'L') ADVANCE(305);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 273:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'L') ADVANCE(221);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 274:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'M') ADVANCE(237);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 275:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'N') ADVANCE(269);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 276:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'N') ADVANCE(262);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 277:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'N') ADVANCE(303);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 278:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'N') ADVANCE(294);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 279:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'O') ADVANCE(270);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 280:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'O') ADVANCE(278);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 281:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'O') ADVANCE(273);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 282:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'O') ADVANCE(281);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 283:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'R') ADVANCE(308);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 284:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'R') ADVANCE(220);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 285:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'R') ADVANCE(236);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 286:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'R') ADVANCE(259);
      if (lookahead == 'U') ADVANCE(293);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 287:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'R') ADVANCE(261);
      if (lookahead == 'U') ADVANCE(296);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 288:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(256);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 289:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(306);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 290:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(299);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 291:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(292);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 292:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(268);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 293:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(258);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 294:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(241);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 295:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(300);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 296:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(260);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 297:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'S') ADVANCE(307);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 298:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'T') ADVANCE(251);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 299:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'T') ADVANCE(255);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 300:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'T') ADVANCE(252);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 301:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'T') ADVANCE(282);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 302:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'T') ADVANCE(266);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 303:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'T') ADVANCE(240);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 304:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'T') ADVANCE(242);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 305:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'T') ADVANCE(244);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 306:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'U') ADVANCE(271);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 307:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'U') ADVANCE(272);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 308:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'V') ADVANCE(257);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 309:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '`') ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 310:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '`') ADVANCE(309);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 311:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'a') ADVANCE(344);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 312:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'a') ADVANCE(331);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 313:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'a') ADVANCE(350);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 314:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'a') ADVANCE(351);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 315:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'a') ADVANCE(332);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 316:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'c') ADVANCE(337);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 317:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'c') ADVANCE(353);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 318:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'c') ADVANCE(336);
      if (lookahead == 's') ADVANCE(315);
      if (lookahead == 't') ADVANCE(356);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 319:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'c') ADVANCE(357);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 320:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'd') ADVANCE(359);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 321:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'd') ADVANCE(323);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 322:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'd') ADVANCE(360);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 323:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'e') ADVANCE(205);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 324:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'e') ADVANCE(246);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 325:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'e') ADVANCE(235);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 326:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'e') ADVANCE(247);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 327:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'e') ADVANCE(227);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 328:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'e') ADVANCE(341);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 329:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'e') ADVANCE(343);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 330:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'e') ADVANCE(231);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 331:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'f') ADVANCE(327);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 332:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'f') ADVANCE(330);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 333:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'h') ADVANCE(328);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 334:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'h') ADVANCE(329);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 335:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'i') ADVANCE(362);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 336:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'i') ADVANCE(363);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 337:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'l') ADVANCE(364);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 338:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'l') ADVANCE(232);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 339:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'l') ADVANCE(233);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 340:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'l') ADVANCE(228);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 341:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'l') ADVANCE(340);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 342:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'l') ADVANCE(230);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 343:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'l') ADVANCE(342);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 344:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'm') ADVANCE(325);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 345:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'm') ADVANCE(313);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 346:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'm') ADVANCE(345);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 347:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'm') ADVANCE(314);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 348:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'm') ADVANCE(347);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 349:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'n') ADVANCE(316);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 350:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'n') ADVANCE(320);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 351:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'n') ADVANCE(322);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 352:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'o') ADVANCE(354);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 353:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'o') ADVANCE(346);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 354:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'o') ADVANCE(338);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 355:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'o') ADVANCE(339);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 356:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'o') ADVANCE(355);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 357:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'o') ADVANCE(348);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 358:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 's') ADVANCE(333);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 359:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 's') ADVANCE(248);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 360:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 's') ADVANCE(249);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 361:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 's') ADVANCE(334);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 362:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 't') ADVANCE(324);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 363:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 't') ADVANCE(326);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 364:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == 'u') ADVANCE(321);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    case 365:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(365);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 161},
  [2] = {.lex_state = 161},
  [3] = {.lex_state = 161},
  [4] = {.lex_state = 161},
  [5] = {.lex_state = 161},
  [6] = {.lex_state = 161},
  [7] = {.lex_state = 198},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 158},
  [17] = {.lex_state = 158},
  [18] = {.lex_state = 158},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 159},
  [23] = {.lex_state = 160},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 159},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND_POUNDUSER_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUNDSYSTEM_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUNDASSISTANT_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUNDTHINKING_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUNDTOOLUSE_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUNDTOOLRESULT_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUNDCITATIONS_COLON] = ACTIONS(1),
    [aux_sym_content_line_token1] = ACTIONS(1),
    [anon_sym_Name_COLON] = ACTIONS(1),
    [anon_sym_ID_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_LTtool_DOT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASHtool_DOT] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [anon_sym_LTinclude] = ACTIONS(1),
    [anon_sym_code] = ACTIONS(1),
    [anon_sym_LT_SLASHinclude_GT] = ACTIONS(1),
    [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = ACTIONS(1),
    [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = ACTIONS(1),
    [anon_sym_LTcite_GT] = ACTIONS(1),
    [anon_sym_LT_SLASHcite_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(14),
    [sym_section_header] = STATE(3),
    [sym_content_line] = STATE(3),
    [sym_empty_line] = STATE(3),
    [sym_tool_name_line] = STATE(13),
    [sym_tool_id_line] = STATE(13),
    [sym_tool_parameter_header] = STATE(13),
    [sym_tool_tag] = STATE(13),
    [sym_code_fence] = STATE(13),
    [sym_html_comment_marker] = STATE(13),
    [sym_include_tag] = STATE(13),
    [sym_safe_shell_tag] = STATE(13),
    [sym_cite_tag] = STATE(13),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND_POUNDUSER_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDSYSTEM_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDASSISTANT_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDTHINKING_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDTOOLUSE_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDTOOLRESULT_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDCITATIONS_COLON] = ACTIONS(5),
    [aux_sym_content_line_token1] = ACTIONS(7),
    [anon_sym_Name_COLON] = ACTIONS(9),
    [anon_sym_ID_COLON] = ACTIONS(11),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(13),
    [anon_sym_LTtool_DOT] = ACTIONS(15),
    [anon_sym_LT_SLASHtool_DOT] = ACTIONS(15),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(17),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(19),
    [anon_sym_DASH_DASH_GT] = ACTIONS(19),
    [anon_sym_LTinclude] = ACTIONS(21),
    [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = ACTIONS(23),
    [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = ACTIONS(23),
    [anon_sym_LTcite_GT] = ACTIONS(25),
    [anon_sym_LT_SLASHcite_GT] = ACTIONS(25),
    [sym_text_content] = ACTIONS(27),
  },
  [STATE(2)] = {
    [sym_section_header] = STATE(2),
    [sym_content_line] = STATE(2),
    [sym_empty_line] = STATE(2),
    [sym_tool_name_line] = STATE(13),
    [sym_tool_id_line] = STATE(13),
    [sym_tool_parameter_header] = STATE(13),
    [sym_tool_tag] = STATE(13),
    [sym_code_fence] = STATE(13),
    [sym_html_comment_marker] = STATE(13),
    [sym_include_tag] = STATE(13),
    [sym_safe_shell_tag] = STATE(13),
    [sym_cite_tag] = STATE(13),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_POUND_POUNDUSER_COLON] = ACTIONS(31),
    [anon_sym_POUND_POUNDSYSTEM_COLON] = ACTIONS(31),
    [anon_sym_POUND_POUNDASSISTANT_COLON] = ACTIONS(31),
    [anon_sym_POUND_POUNDTHINKING_COLON] = ACTIONS(31),
    [anon_sym_POUND_POUNDTOOLUSE_COLON] = ACTIONS(31),
    [anon_sym_POUND_POUNDTOOLRESULT_COLON] = ACTIONS(31),
    [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = ACTIONS(31),
    [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = ACTIONS(31),
    [anon_sym_POUND_POUNDCITATIONS_COLON] = ACTIONS(31),
    [aux_sym_content_line_token1] = ACTIONS(34),
    [anon_sym_Name_COLON] = ACTIONS(37),
    [anon_sym_ID_COLON] = ACTIONS(40),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(43),
    [anon_sym_LTtool_DOT] = ACTIONS(46),
    [anon_sym_LT_SLASHtool_DOT] = ACTIONS(46),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(49),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(52),
    [anon_sym_DASH_DASH_GT] = ACTIONS(52),
    [anon_sym_LTinclude] = ACTIONS(55),
    [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = ACTIONS(58),
    [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = ACTIONS(58),
    [anon_sym_LTcite_GT] = ACTIONS(61),
    [anon_sym_LT_SLASHcite_GT] = ACTIONS(61),
    [sym_text_content] = ACTIONS(64),
  },
  [STATE(3)] = {
    [sym_section_header] = STATE(2),
    [sym_content_line] = STATE(2),
    [sym_empty_line] = STATE(2),
    [sym_tool_name_line] = STATE(13),
    [sym_tool_id_line] = STATE(13),
    [sym_tool_parameter_header] = STATE(13),
    [sym_tool_tag] = STATE(13),
    [sym_code_fence] = STATE(13),
    [sym_html_comment_marker] = STATE(13),
    [sym_include_tag] = STATE(13),
    [sym_safe_shell_tag] = STATE(13),
    [sym_cite_tag] = STATE(13),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_POUND_POUNDUSER_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDSYSTEM_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDASSISTANT_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDTHINKING_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDTOOLUSE_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDTOOLRESULT_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = ACTIONS(5),
    [anon_sym_POUND_POUNDCITATIONS_COLON] = ACTIONS(5),
    [aux_sym_content_line_token1] = ACTIONS(7),
    [anon_sym_Name_COLON] = ACTIONS(9),
    [anon_sym_ID_COLON] = ACTIONS(11),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(13),
    [anon_sym_LTtool_DOT] = ACTIONS(15),
    [anon_sym_LT_SLASHtool_DOT] = ACTIONS(15),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(17),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(19),
    [anon_sym_DASH_DASH_GT] = ACTIONS(19),
    [anon_sym_LTinclude] = ACTIONS(21),
    [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = ACTIONS(23),
    [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = ACTIONS(23),
    [anon_sym_LTcite_GT] = ACTIONS(25),
    [anon_sym_LT_SLASHcite_GT] = ACTIONS(25),
    [sym_text_content] = ACTIONS(27),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_POUND_POUNDUSER_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUNDSYSTEM_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUNDASSISTANT_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUNDTHINKING_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUNDTOOLUSE_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUNDTOOLRESULT_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUNDCITATIONS_COLON] = ACTIONS(71),
    [aux_sym_content_line_token1] = ACTIONS(71),
    [anon_sym_Name_COLON] = ACTIONS(71),
    [anon_sym_ID_COLON] = ACTIONS(71),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(71),
    [anon_sym_LTtool_DOT] = ACTIONS(71),
    [anon_sym_LT_SLASHtool_DOT] = ACTIONS(71),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(71),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(71),
    [anon_sym_DASH_DASH_GT] = ACTIONS(71),
    [anon_sym_LTinclude] = ACTIONS(71),
    [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = ACTIONS(71),
    [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = ACTIONS(71),
    [anon_sym_LTcite_GT] = ACTIONS(71),
    [anon_sym_LT_SLASHcite_GT] = ACTIONS(71),
    [sym_text_content] = ACTIONS(71),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [anon_sym_POUND_POUNDUSER_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUNDSYSTEM_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUNDASSISTANT_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUNDTHINKING_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUNDTOOLUSE_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUNDTOOLRESULT_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUNDCITATIONS_COLON] = ACTIONS(75),
    [aux_sym_content_line_token1] = ACTIONS(75),
    [anon_sym_Name_COLON] = ACTIONS(75),
    [anon_sym_ID_COLON] = ACTIONS(75),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(75),
    [anon_sym_LTtool_DOT] = ACTIONS(75),
    [anon_sym_LT_SLASHtool_DOT] = ACTIONS(75),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(75),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(75),
    [anon_sym_DASH_DASH_GT] = ACTIONS(75),
    [anon_sym_LTinclude] = ACTIONS(75),
    [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = ACTIONS(75),
    [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = ACTIONS(75),
    [anon_sym_LTcite_GT] = ACTIONS(75),
    [anon_sym_LT_SLASHcite_GT] = ACTIONS(75),
    [sym_text_content] = ACTIONS(75),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_POUND_POUNDUSER_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUNDSYSTEM_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUNDASSISTANT_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUNDTHINKING_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUNDTOOLUSE_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUNDTOOLRESULT_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUNDSERVERTOOLUSE_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUNDSERVERTOOLRESULT_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUNDCITATIONS_COLON] = ACTIONS(79),
    [aux_sym_content_line_token1] = ACTIONS(79),
    [anon_sym_Name_COLON] = ACTIONS(79),
    [anon_sym_ID_COLON] = ACTIONS(79),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(79),
    [anon_sym_LTtool_DOT] = ACTIONS(79),
    [anon_sym_LT_SLASHtool_DOT] = ACTIONS(79),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(79),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(79),
    [anon_sym_DASH_DASH_GT] = ACTIONS(79),
    [anon_sym_LTinclude] = ACTIONS(79),
    [anon_sym_LTsafe_DASHshell_DASHcommands_GT] = ACTIONS(79),
    [anon_sym_LT_SLASHsafe_DASHshell_DASHcommands_GT] = ACTIONS(79),
    [anon_sym_LTcite_GT] = ACTIONS(79),
    [anon_sym_LT_SLASHcite_GT] = ACTIONS(79),
    [sym_text_content] = ACTIONS(79),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(81), 1,
      aux_sym_content_line_token1,
    ACTIONS(83), 1,
      aux_sym_code_fence_token1,
  [7] = 2,
    ACTIONS(85), 1,
      aux_sym_tool_name_line_token1,
    ACTIONS(87), 1,
      anon_sym_GT,
  [14] = 1,
    ACTIONS(89), 1,
      aux_sym_content_line_token1,
  [18] = 1,
    ACTIONS(91), 1,
      aux_sym_tool_name_line_token1,
  [22] = 1,
    ACTIONS(93), 1,
      aux_sym_content_line_token1,
  [26] = 1,
    ACTIONS(95), 1,
      aux_sym_content_line_token1,
  [30] = 1,
    ACTIONS(97), 1,
      aux_sym_content_line_token1,
  [34] = 1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [38] = 1,
    ACTIONS(101), 1,
      aux_sym_tool_name_line_token1,
  [42] = 1,
    ACTIONS(103), 1,
      aux_sym_tool_name_line_token2,
  [46] = 1,
    ACTIONS(105), 1,
      aux_sym_tool_name_line_token2,
  [50] = 1,
    ACTIONS(107), 1,
      aux_sym_tool_name_line_token2,
  [54] = 1,
    ACTIONS(109), 1,
      anon_sym_GT,
  [58] = 1,
    ACTIONS(111), 1,
      aux_sym_content_line_token1,
  [62] = 1,
    ACTIONS(113), 1,
      anon_sym_code,
  [66] = 1,
    ACTIONS(115), 1,
      aux_sym_include_tag_token1,
  [70] = 1,
    ACTIONS(117), 1,
      aux_sym_tool_tag_token1,
  [74] = 1,
    ACTIONS(119), 1,
      aux_sym_tool_name_line_token1,
  [78] = 1,
    ACTIONS(121), 1,
      aux_sym_content_line_token1,
  [82] = 1,
    ACTIONS(123), 1,
      aux_sym_content_line_token1,
  [86] = 1,
    ACTIONS(125), 1,
      aux_sym_content_line_token1,
  [90] = 1,
    ACTIONS(127), 1,
      aux_sym_content_line_token1,
  [94] = 1,
    ACTIONS(129), 1,
      anon_sym_GT,
  [98] = 1,
    ACTIONS(131), 1,
      anon_sym_LT_SLASHinclude_GT,
  [102] = 1,
    ACTIONS(133), 1,
      aux_sym_include_tag_token1,
  [106] = 1,
    ACTIONS(135), 1,
      aux_sym_content_line_token1,
  [110] = 1,
    ACTIONS(137), 1,
      anon_sym_LT_SLASHinclude_GT,
  [114] = 1,
    ACTIONS(139), 1,
      aux_sym_content_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 7,
  [SMALL_STATE(9)] = 14,
  [SMALL_STATE(10)] = 18,
  [SMALL_STATE(11)] = 22,
  [SMALL_STATE(12)] = 26,
  [SMALL_STATE(13)] = 30,
  [SMALL_STATE(14)] = 34,
  [SMALL_STATE(15)] = 38,
  [SMALL_STATE(16)] = 42,
  [SMALL_STATE(17)] = 46,
  [SMALL_STATE(18)] = 50,
  [SMALL_STATE(19)] = 54,
  [SMALL_STATE(20)] = 58,
  [SMALL_STATE(21)] = 62,
  [SMALL_STATE(22)] = 66,
  [SMALL_STATE(23)] = 70,
  [SMALL_STATE(24)] = 74,
  [SMALL_STATE(25)] = 78,
  [SMALL_STATE(26)] = 82,
  [SMALL_STATE(27)] = 86,
  [SMALL_STATE(28)] = 90,
  [SMALL_STATE(29)] = 94,
  [SMALL_STATE(30)] = 98,
  [SMALL_STATE(31)] = 102,
  [SMALL_STATE(32)] = 106,
  [SMALL_STATE(33)] = 110,
  [SMALL_STATE(34)] = 114,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_line, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_line, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_line, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_fence, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_tag, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_safe_shell_tag, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cite_tag, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [99] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_fence, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_name_line, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_id_line, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_parameter_header, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_comment_marker, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_tag, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_tag, 6, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_greger(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
