/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_user_header = 1,
  sym_system_header = 2,
  sym_assistant_header = 3,
  sym_thinking_header = 4,
  sym_tool_use_header = 5,
  sym_tool_result_header = 6,
  sym_server_tool_use_header = 7,
  sym_server_tool_result_header = 8,
  sym_citations_header = 9,
  anon_sym_LF = 10,
  anon_sym_LTcite_GT = 11,
  aux_sym_cite_tag_token1 = 12,
  anon_sym_LT_SLASHcite_GT = 13,
  anon_sym_Name_COLON = 14,
  aux_sym_tool_name_line_token1 = 15,
  anon_sym_ID_COLON = 16,
  anon_sym_POUND_POUND_POUND = 17,
  anon_sym_Title_COLON = 18,
  aux_sym_citation_title_token1 = 19,
  anon_sym_Citedtext_COLON = 20,
  anon_sym_Encryptedindex_COLON = 21,
  sym_identifier = 22,
  sym_url = 23,
  sym_tool_block_start = 24,
  sym_tool_block_end = 25,
  sym_tool_block_content = 26,
  sym__text = 27,
  sym_source_file = 28,
  sym_section = 29,
  sym_user_section = 30,
  sym_system_section = 31,
  sym_assistant_section = 32,
  sym_thinking_section = 33,
  sym_tool_use_section = 34,
  sym_tool_result_section = 35,
  sym_server_tool_use_section = 36,
  sym_server_tool_result_section = 37,
  sym_citations_section = 38,
  sym_content = 39,
  sym_content_line = 40,
  sym_cite_tag = 41,
  sym_system_content = 42,
  sym_tool_use_content = 43,
  sym_tool_result_content = 44,
  sym_citations_content = 45,
  sym_tool_name_line = 46,
  sym_tool_id_line = 47,
  sym_tool_parameter = 48,
  sym_tool_param_block = 49,
  sym_tool_result_id_line = 50,
  sym_tool_result_block = 51,
  sym_citation_entry = 52,
  sym_citation_title = 53,
  sym_citation_text = 54,
  sym_citation_index = 55,
  sym_newline = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_content_repeat1 = 58,
  aux_sym_content_line_repeat1 = 59,
  aux_sym_cite_tag_repeat1 = 60,
  aux_sym_tool_use_content_repeat1 = 61,
  aux_sym_tool_result_content_repeat1 = 62,
  aux_sym_citations_content_repeat1 = 63,
  aux_sym_tool_param_block_repeat1 = 64,
  aux_sym_citation_entry_repeat1 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_user_header] = "user_header",
  [sym_system_header] = "system_header",
  [sym_assistant_header] = "assistant_header",
  [sym_thinking_header] = "thinking_header",
  [sym_tool_use_header] = "tool_use_header",
  [sym_tool_result_header] = "tool_result_header",
  [sym_server_tool_use_header] = "server_tool_use_header",
  [sym_server_tool_result_header] = "server_tool_result_header",
  [sym_citations_header] = "citations_header",
  [anon_sym_LF] = "\n",
  [anon_sym_LTcite_GT] = "<cite>",
  [aux_sym_cite_tag_token1] = "cite_tag_token1",
  [anon_sym_LT_SLASHcite_GT] = "</cite>",
  [anon_sym_Name_COLON] = "Name:",
  [aux_sym_tool_name_line_token1] = "tool_name_line_token1",
  [anon_sym_ID_COLON] = "ID:",
  [anon_sym_POUND_POUND_POUND] = "###",
  [anon_sym_Title_COLON] = "Title:",
  [aux_sym_citation_title_token1] = "citation_title_token1",
  [anon_sym_Citedtext_COLON] = "Cited text:",
  [anon_sym_Encryptedindex_COLON] = "Encrypted index:",
  [sym_identifier] = "identifier",
  [sym_url] = "url",
  [sym_tool_block_start] = "tool_block_start",
  [sym_tool_block_end] = "tool_block_end",
  [sym_tool_block_content] = "tool_block_content",
  [sym__text] = "text",
  [sym_source_file] = "source_file",
  [sym_section] = "section",
  [sym_user_section] = "user_section",
  [sym_system_section] = "system_section",
  [sym_assistant_section] = "assistant_section",
  [sym_thinking_section] = "thinking_section",
  [sym_tool_use_section] = "tool_use_section",
  [sym_tool_result_section] = "tool_result_section",
  [sym_server_tool_use_section] = "server_tool_use_section",
  [sym_server_tool_result_section] = "server_tool_result_section",
  [sym_citations_section] = "citations_section",
  [sym_content] = "section_content",
  [sym_content_line] = "content_line",
  [sym_cite_tag] = "cite_tag",
  [sym_system_content] = "section_content",
  [sym_tool_use_content] = "tool_use_content",
  [sym_tool_result_content] = "tool_result_content",
  [sym_citations_content] = "citations_content",
  [sym_tool_name_line] = "tool_name_line",
  [sym_tool_id_line] = "tool_id_line",
  [sym_tool_parameter] = "tool_parameter",
  [sym_tool_param_block] = "tool_param_block",
  [sym_tool_result_id_line] = "tool_result_id_line",
  [sym_tool_result_block] = "tool_result_block",
  [sym_citation_entry] = "citation_entry",
  [sym_citation_title] = "citation_title",
  [sym_citation_text] = "citation_text",
  [sym_citation_index] = "citation_index",
  [sym_newline] = "newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_content_line_repeat1] = "content_line_repeat1",
  [aux_sym_cite_tag_repeat1] = "cite_tag_repeat1",
  [aux_sym_tool_use_content_repeat1] = "tool_use_content_repeat1",
  [aux_sym_tool_result_content_repeat1] = "tool_result_content_repeat1",
  [aux_sym_citations_content_repeat1] = "citations_content_repeat1",
  [aux_sym_tool_param_block_repeat1] = "tool_param_block_repeat1",
  [aux_sym_citation_entry_repeat1] = "citation_entry_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_user_header] = sym_user_header,
  [sym_system_header] = sym_system_header,
  [sym_assistant_header] = sym_assistant_header,
  [sym_thinking_header] = sym_thinking_header,
  [sym_tool_use_header] = sym_tool_use_header,
  [sym_tool_result_header] = sym_tool_result_header,
  [sym_server_tool_use_header] = sym_server_tool_use_header,
  [sym_server_tool_result_header] = sym_server_tool_result_header,
  [sym_citations_header] = sym_citations_header,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LTcite_GT] = anon_sym_LTcite_GT,
  [aux_sym_cite_tag_token1] = aux_sym_cite_tag_token1,
  [anon_sym_LT_SLASHcite_GT] = anon_sym_LT_SLASHcite_GT,
  [anon_sym_Name_COLON] = anon_sym_Name_COLON,
  [aux_sym_tool_name_line_token1] = aux_sym_tool_name_line_token1,
  [anon_sym_ID_COLON] = anon_sym_ID_COLON,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [anon_sym_Title_COLON] = anon_sym_Title_COLON,
  [aux_sym_citation_title_token1] = aux_sym_citation_title_token1,
  [anon_sym_Citedtext_COLON] = anon_sym_Citedtext_COLON,
  [anon_sym_Encryptedindex_COLON] = anon_sym_Encryptedindex_COLON,
  [sym_identifier] = sym_identifier,
  [sym_url] = sym_url,
  [sym_tool_block_start] = sym_tool_block_start,
  [sym_tool_block_end] = sym_tool_block_end,
  [sym_tool_block_content] = sym_tool_block_content,
  [sym__text] = sym__text,
  [sym_source_file] = sym_source_file,
  [sym_section] = sym_section,
  [sym_user_section] = sym_user_section,
  [sym_system_section] = sym_system_section,
  [sym_assistant_section] = sym_assistant_section,
  [sym_thinking_section] = sym_thinking_section,
  [sym_tool_use_section] = sym_tool_use_section,
  [sym_tool_result_section] = sym_tool_result_section,
  [sym_server_tool_use_section] = sym_server_tool_use_section,
  [sym_server_tool_result_section] = sym_server_tool_result_section,
  [sym_citations_section] = sym_citations_section,
  [sym_content] = sym_content,
  [sym_content_line] = sym_content_line,
  [sym_cite_tag] = sym_cite_tag,
  [sym_system_content] = sym_content,
  [sym_tool_use_content] = sym_tool_use_content,
  [sym_tool_result_content] = sym_tool_result_content,
  [sym_citations_content] = sym_citations_content,
  [sym_tool_name_line] = sym_tool_name_line,
  [sym_tool_id_line] = sym_tool_id_line,
  [sym_tool_parameter] = sym_tool_parameter,
  [sym_tool_param_block] = sym_tool_param_block,
  [sym_tool_result_id_line] = sym_tool_result_id_line,
  [sym_tool_result_block] = sym_tool_result_block,
  [sym_citation_entry] = sym_citation_entry,
  [sym_citation_title] = sym_citation_title,
  [sym_citation_text] = sym_citation_text,
  [sym_citation_index] = sym_citation_index,
  [sym_newline] = sym_newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_content_line_repeat1] = aux_sym_content_line_repeat1,
  [aux_sym_cite_tag_repeat1] = aux_sym_cite_tag_repeat1,
  [aux_sym_tool_use_content_repeat1] = aux_sym_tool_use_content_repeat1,
  [aux_sym_tool_result_content_repeat1] = aux_sym_tool_result_content_repeat1,
  [aux_sym_citations_content_repeat1] = aux_sym_citations_content_repeat1,
  [aux_sym_tool_param_block_repeat1] = aux_sym_tool_param_block_repeat1,
  [aux_sym_citation_entry_repeat1] = aux_sym_citation_entry_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_user_header] = {
    .visible = true,
    .named = true,
  },
  [sym_system_header] = {
    .visible = true,
    .named = true,
  },
  [sym_assistant_header] = {
    .visible = true,
    .named = true,
  },
  [sym_thinking_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_use_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_header] = {
    .visible = true,
    .named = true,
  },
  [sym_server_tool_use_header] = {
    .visible = true,
    .named = true,
  },
  [sym_server_tool_result_header] = {
    .visible = true,
    .named = true,
  },
  [sym_citations_header] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTcite_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cite_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_SLASHcite_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Name_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tool_name_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_ID_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Title_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_citation_title_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Citedtext_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Encryptedindex_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_block_start] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_block_end] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_user_section] = {
    .visible = true,
    .named = true,
  },
  [sym_system_section] = {
    .visible = true,
    .named = true,
  },
  [sym_assistant_section] = {
    .visible = true,
    .named = true,
  },
  [sym_thinking_section] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_use_section] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_section] = {
    .visible = true,
    .named = true,
  },
  [sym_server_tool_use_section] = {
    .visible = true,
    .named = true,
  },
  [sym_server_tool_result_section] = {
    .visible = true,
    .named = true,
  },
  [sym_citations_section] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_cite_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_system_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_use_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_content] = {
    .visible = true,
    .named = true,
  },
  [sym_citations_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_name_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_id_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_param_block] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_id_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_block] = {
    .visible = true,
    .named = true,
  },
  [sym_citation_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_citation_title] = {
    .visible = true,
    .named = true,
  },
  [sym_citation_text] = {
    .visible = true,
    .named = true,
  },
  [sym_citation_index] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cite_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tool_use_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tool_result_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_citations_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tool_param_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_citation_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_id = 2,
  field_index = 3,
  field_name = 4,
  field_param_name = 5,
  field_param_value = 6,
  field_text = 7,
  field_title = 8,
  field_url = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_id] = "id",
  [field_index] = "index",
  [field_name] = "name",
  [field_param_name] = "param_name",
  [field_param_value] = "param_value",
  [field_text] = "text",
  [field_title] = "title",
  [field_url] = "url",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_name, 2},
  [2] =
    {field_id, 2},
  [3] =
    {field_url, 2},
  [4] =
    {field_param_name, 2},
    {field_param_value, 5},
  [6] =
    {field_title, 2},
  [7] =
    {field_text, 2},
  [8] =
    {field_index, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 21,
  [35] = 35,
  [36] = 36,
  [37] = 21,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(141);
      if (lookahead == '\n') ADVANCE(151);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == 'I') ADVANCE(170);
      if (lookahead == 'N') ADVANCE(171);
      if (lookahead == 'T') ADVANCE(174);
      if (lookahead == 'h') ADVANCE(180);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(151);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(153);
      if (lookahead != 0) ADVANCE(154);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(142);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(143);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(145);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(146);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(144);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(150);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(147);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(148);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(149);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(76);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(114);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(91);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(130);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(77);
      END_STATE();
    case 16:
      if (lookahead == '#') ADVANCE(17);
      END_STATE();
    case 17:
      ADVANCE_MAP(
        '#', 159,
        'A', 81,
        'C', 54,
        'S', 44,
        'T', 53,
        'U', 78,
        '\t', 40,
        ' ', 40,
      );
      END_STATE();
    case 18:
      if (lookahead == '/') ADVANCE(101);
      END_STATE();
    case 19:
      if (lookahead == '/') ADVANCE(101);
      if (lookahead == 'c') ADVANCE(113);
      END_STATE();
    case 20:
      if (lookahead == '/') ADVANCE(139);
      END_STATE();
    case 21:
      if (lookahead == '/') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == ':') ADVANCE(158);
      END_STATE();
    case 23:
      if (lookahead == ':') ADVANCE(156);
      END_STATE();
    case 24:
      if (lookahead == ':') ADVANCE(21);
      END_STATE();
    case 25:
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == ':') ADVANCE(160);
      END_STATE();
    case 27:
      if (lookahead == ':') ADVANCE(2);
      END_STATE();
    case 28:
      if (lookahead == ':') ADVANCE(163);
      END_STATE();
    case 29:
      if (lookahead == ':') ADVANCE(164);
      END_STATE();
    case 30:
      if (lookahead == ':') ADVANCE(3);
      END_STATE();
    case 31:
      if (lookahead == ':') ADVANCE(4);
      END_STATE();
    case 32:
      if (lookahead == ':') ADVANCE(5);
      END_STATE();
    case 33:
      if (lookahead == ':') ADVANCE(6);
      END_STATE();
    case 34:
      if (lookahead == ':') ADVANCE(7);
      END_STATE();
    case 35:
      if (lookahead == ':') ADVANCE(8);
      END_STATE();
    case 36:
      if (lookahead == ':') ADVANCE(9);
      END_STATE();
    case 37:
      if (lookahead == ':') ADVANCE(10);
      END_STATE();
    case 38:
      if (lookahead == '>') ADVANCE(152);
      END_STATE();
    case 39:
      if (lookahead == '>') ADVANCE(155);
      END_STATE();
    case 40:
      if (lookahead == 'A') ADVANCE(81);
      if (lookahead == 'C') ADVANCE(54);
      if (lookahead == 'S') ADVANCE(44);
      if (lookahead == 'T') ADVANCE(53);
      if (lookahead == 'U') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 41:
      if (lookahead == 'A') ADVANCE(92);
      END_STATE();
    case 42:
      if (lookahead == 'A') ADVANCE(67);
      END_STATE();
    case 43:
      if (lookahead == 'D') ADVANCE(22);
      END_STATE();
    case 44:
      if (lookahead == 'E') ADVANCE(73);
      if (lookahead == 'Y') ADVANCE(80);
      END_STATE();
    case 45:
      if (lookahead == 'E') ADVANCE(64);
      END_STATE();
    case 46:
      if (lookahead == 'E') ADVANCE(74);
      END_STATE();
    case 47:
      if (lookahead == 'E') ADVANCE(75);
      END_STATE();
    case 48:
      if (lookahead == 'E') ADVANCE(79);
      END_STATE();
    case 49:
      if (lookahead == 'E') ADVANCE(32);
      END_STATE();
    case 50:
      if (lookahead == 'E') ADVANCE(36);
      END_STATE();
    case 51:
      if (lookahead == 'E') ADVANCE(87);
      END_STATE();
    case 52:
      if (lookahead == 'G') ADVANCE(31);
      END_STATE();
    case 53:
      if (lookahead == 'H') ADVANCE(55);
      if (lookahead == 'O') ADVANCE(69);
      END_STATE();
    case 54:
      if (lookahead == 'I') ADVANCE(88);
      END_STATE();
    case 55:
      if (lookahead == 'I') ADVANCE(65);
      END_STATE();
    case 56:
      if (lookahead == 'I') ADVANCE(70);
      END_STATE();
    case 57:
      if (lookahead == 'I') ADVANCE(66);
      END_STATE();
    case 58:
      if (lookahead == 'I') ADVANCE(84);
      END_STATE();
    case 59:
      if (lookahead == 'K') ADVANCE(57);
      END_STATE();
    case 60:
      if (lookahead == 'L') ADVANCE(11);
      END_STATE();
    case 61:
      if (lookahead == 'L') ADVANCE(94);
      END_STATE();
    case 62:
      if (lookahead == 'L') ADVANCE(95);
      END_STATE();
    case 63:
      if (lookahead == 'L') ADVANCE(15);
      END_STATE();
    case 64:
      if (lookahead == 'M') ADVANCE(30);
      END_STATE();
    case 65:
      if (lookahead == 'N') ADVANCE(59);
      END_STATE();
    case 66:
      if (lookahead == 'N') ADVANCE(52);
      END_STATE();
    case 67:
      if (lookahead == 'N') ADVANCE(93);
      END_STATE();
    case 68:
      if (lookahead == 'N') ADVANCE(85);
      END_STATE();
    case 69:
      if (lookahead == 'O') ADVANCE(60);
      END_STATE();
    case 70:
      if (lookahead == 'O') ADVANCE(68);
      END_STATE();
    case 71:
      if (lookahead == 'O') ADVANCE(63);
      END_STATE();
    case 72:
      if (lookahead == 'O') ADVANCE(71);
      END_STATE();
    case 73:
      if (lookahead == 'R') ADVANCE(98);
      END_STATE();
    case 74:
      if (lookahead == 'R') ADVANCE(27);
      END_STATE();
    case 75:
      if (lookahead == 'R') ADVANCE(13);
      END_STATE();
    case 76:
      if (lookahead == 'R') ADVANCE(48);
      if (lookahead == 'U') ADVANCE(83);
      END_STATE();
    case 77:
      if (lookahead == 'R') ADVANCE(51);
      if (lookahead == 'U') ADVANCE(86);
      END_STATE();
    case 78:
      if (lookahead == 'S') ADVANCE(46);
      END_STATE();
    case 79:
      if (lookahead == 'S') ADVANCE(96);
      END_STATE();
    case 80:
      if (lookahead == 'S') ADVANCE(89);
      END_STATE();
    case 81:
      if (lookahead == 'S') ADVANCE(82);
      END_STATE();
    case 82:
      if (lookahead == 'S') ADVANCE(58);
      END_STATE();
    case 83:
      if (lookahead == 'S') ADVANCE(49);
      END_STATE();
    case 84:
      if (lookahead == 'S') ADVANCE(90);
      END_STATE();
    case 85:
      if (lookahead == 'S') ADVANCE(34);
      END_STATE();
    case 86:
      if (lookahead == 'S') ADVANCE(50);
      END_STATE();
    case 87:
      if (lookahead == 'S') ADVANCE(97);
      END_STATE();
    case 88:
      if (lookahead == 'T') ADVANCE(41);
      END_STATE();
    case 89:
      if (lookahead == 'T') ADVANCE(45);
      END_STATE();
    case 90:
      if (lookahead == 'T') ADVANCE(42);
      END_STATE();
    case 91:
      if (lookahead == 'T') ADVANCE(72);
      END_STATE();
    case 92:
      if (lookahead == 'T') ADVANCE(56);
      END_STATE();
    case 93:
      if (lookahead == 'T') ADVANCE(33);
      END_STATE();
    case 94:
      if (lookahead == 'T') ADVANCE(35);
      END_STATE();
    case 95:
      if (lookahead == 'T') ADVANCE(37);
      END_STATE();
    case 96:
      if (lookahead == 'U') ADVANCE(61);
      END_STATE();
    case 97:
      if (lookahead == 'U') ADVANCE(62);
      END_STATE();
    case 98:
      if (lookahead == 'V') ADVANCE(47);
      END_STATE();
    case 99:
      if (lookahead == 'a') ADVANCE(119);
      END_STATE();
    case 100:
      if (lookahead == 'c') ADVANCE(124);
      END_STATE();
    case 101:
      if (lookahead == 'c') ADVANCE(117);
      END_STATE();
    case 102:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 103:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 104:
      if (lookahead == 'd') ADVANCE(109);
      END_STATE();
    case 105:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 106:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 107:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 108:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 109:
      if (lookahead == 'e') ADVANCE(135);
      END_STATE();
    case 110:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 111:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 112:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 113:
      if (lookahead == 'i') ADVANCE(125);
      END_STATE();
    case 114:
      if (lookahead == 'i') ADVANCE(121);
      END_STATE();
    case 115:
      if (lookahead == 'i') ADVANCE(126);
      END_STATE();
    case 116:
      if (lookahead == 'i') ADVANCE(128);
      END_STATE();
    case 117:
      if (lookahead == 'i') ADVANCE(132);
      END_STATE();
    case 118:
      if (lookahead == 'l') ADVANCE(111);
      END_STATE();
    case 119:
      if (lookahead == 'm') ADVANCE(110);
      END_STATE();
    case 120:
      if (lookahead == 'n') ADVANCE(100);
      END_STATE();
    case 121:
      if (lookahead == 'n') ADVANCE(104);
      END_STATE();
    case 122:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 123:
      if (lookahead == 'p') ADVANCE(133);
      END_STATE();
    case 124:
      if (lookahead == 'r') ADVANCE(136);
      END_STATE();
    case 125:
      if (lookahead == 't') ADVANCE(105);
      END_STATE();
    case 126:
      if (lookahead == 't') ADVANCE(118);
      END_STATE();
    case 127:
      if (lookahead == 't') ADVANCE(122);
      END_STATE();
    case 128:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 129:
      if (lookahead == 't') ADVANCE(127);
      END_STATE();
    case 130:
      if (lookahead == 't') ADVANCE(107);
      END_STATE();
    case 131:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 132:
      if (lookahead == 't') ADVANCE(108);
      END_STATE();
    case 133:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 134:
      if (lookahead == 'x') ADVANCE(131);
      END_STATE();
    case 135:
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 136:
      if (lookahead == 'y') ADVANCE(123);
      END_STATE();
    case 137:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(137);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 138:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 139:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(182);
      END_STATE();
    case 140:
      if (eof) ADVANCE(141);
      ADVANCE_MAP(
        '\n', 151,
        '#', 16,
        'C', 116,
        'E', 120,
        'I', 43,
        'N', 99,
        'T', 115,
        'h', 129,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(140);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_user_header);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_system_header);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_assistant_header);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_thinking_header);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_tool_use_header);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_tool_result_header);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_server_tool_use_header);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_server_tool_result_header);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_citations_header);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_LTcite_GT);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_cite_tag_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '<') ADVANCE(154);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_cite_tag_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<') ADVANCE(154);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_LT_SLASHcite_GT);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_Name_COLON);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_tool_name_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(157);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_ID_COLON);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_Title_COLON);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_citation_title_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_citation_title_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(162);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_Citedtext_COLON);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_Encryptedindex_COLON);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(158);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(156);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 's') ADVANCE(168);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(160);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(165);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(176);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(166);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(169);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(178);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(173);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(172);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(167);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(175);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(177);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(179);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(181);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(182);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 140},
  [5] = {.lex_state = 140},
  [6] = {.lex_state = 140},
  [7] = {.lex_state = 140},
  [8] = {.lex_state = 140},
  [9] = {.lex_state = 140},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 140},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 140, .external_lex_state = 3},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 140, .external_lex_state = 3},
  [20] = {.lex_state = 140, .external_lex_state = 3},
  [21] = {.lex_state = 140},
  [22] = {.lex_state = 140, .external_lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 140},
  [27] = {.lex_state = 140},
  [28] = {.lex_state = 140},
  [29] = {.lex_state = 140},
  [30] = {.lex_state = 140},
  [31] = {.lex_state = 140},
  [32] = {.lex_state = 140},
  [33] = {.lex_state = 140},
  [34] = {.lex_state = 140, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 140, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 140, .external_lex_state = 3},
  [39] = {.lex_state = 140, .external_lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 4},
  [57] = {.lex_state = 0, .external_lex_state = 4},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 4},
  [60] = {.lex_state = 0, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 157},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 137},
  [68] = {.lex_state = 157},
  [69] = {.lex_state = 140},
  [70] = {.lex_state = 157},
  [71] = {.lex_state = 157},
  [72] = {.lex_state = 157},
  [73] = {.lex_state = 157},
  [74] = {.lex_state = 157},
  [75] = {.lex_state = 137},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 138},
  [78] = {.lex_state = 138},
  [79] = {.lex_state = 138},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 137},
  [85] = {.lex_state = 137},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 157},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_user_header] = ACTIONS(1),
    [sym_system_header] = ACTIONS(1),
    [sym_assistant_header] = ACTIONS(1),
    [sym_thinking_header] = ACTIONS(1),
    [sym_tool_use_header] = ACTIONS(1),
    [sym_tool_result_header] = ACTIONS(1),
    [sym_server_tool_use_header] = ACTIONS(1),
    [sym_server_tool_result_header] = ACTIONS(1),
    [sym_citations_header] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_LTcite_GT] = ACTIONS(1),
    [anon_sym_LT_SLASHcite_GT] = ACTIONS(1),
    [anon_sym_Name_COLON] = ACTIONS(1),
    [anon_sym_ID_COLON] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_Title_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_url] = ACTIONS(1),
    [sym_tool_block_start] = ACTIONS(1),
    [sym_tool_block_end] = ACTIONS(1),
    [sym_tool_block_content] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(88),
    [sym_section] = STATE(2),
    [sym_user_section] = STATE(49),
    [sym_system_section] = STATE(49),
    [sym_assistant_section] = STATE(49),
    [sym_thinking_section] = STATE(49),
    [sym_tool_use_section] = STATE(49),
    [sym_tool_result_section] = STATE(49),
    [sym_server_tool_use_section] = STATE(49),
    [sym_server_tool_result_section] = STATE(49),
    [sym_citations_section] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_user_header] = ACTIONS(5),
    [sym_system_header] = ACTIONS(7),
    [sym_assistant_header] = ACTIONS(9),
    [sym_thinking_header] = ACTIONS(11),
    [sym_tool_use_header] = ACTIONS(13),
    [sym_tool_result_header] = ACTIONS(15),
    [sym_server_tool_use_header] = ACTIONS(17),
    [sym_server_tool_result_header] = ACTIONS(19),
    [sym_citations_header] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      sym_user_header,
    ACTIONS(7), 1,
      sym_system_header,
    ACTIONS(9), 1,
      sym_assistant_header,
    ACTIONS(11), 1,
      sym_thinking_header,
    ACTIONS(13), 1,
      sym_tool_use_header,
    ACTIONS(15), 1,
      sym_tool_result_header,
    ACTIONS(17), 1,
      sym_server_tool_use_header,
    ACTIONS(19), 1,
      sym_server_tool_result_header,
    ACTIONS(21), 1,
      sym_citations_header,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_section,
      aux_sym_source_file_repeat1,
    STATE(49), 9,
      sym_user_section,
      sym_system_section,
      sym_assistant_section,
      sym_thinking_section,
      sym_tool_use_section,
      sym_tool_result_section,
      sym_server_tool_use_section,
      sym_server_tool_result_section,
      sym_citations_section,
  [46] = 12,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      sym_user_header,
    ACTIONS(30), 1,
      sym_system_header,
    ACTIONS(33), 1,
      sym_assistant_header,
    ACTIONS(36), 1,
      sym_thinking_header,
    ACTIONS(39), 1,
      sym_tool_use_header,
    ACTIONS(42), 1,
      sym_tool_result_header,
    ACTIONS(45), 1,
      sym_server_tool_use_header,
    ACTIONS(48), 1,
      sym_server_tool_result_header,
    ACTIONS(51), 1,
      sym_citations_header,
    STATE(3), 2,
      sym_section,
      aux_sym_source_file_repeat1,
    STATE(49), 9,
      sym_user_section,
      sym_system_section,
      sym_assistant_section,
      sym_thinking_section,
      sym_tool_use_section,
      sym_tool_result_section,
      sym_server_tool_use_section,
      sym_server_tool_result_section,
      sym_citations_section,
  [92] = 5,
    ACTIONS(56), 1,
      anon_sym_Title_COLON,
    ACTIONS(58), 1,
      anon_sym_Citedtext_COLON,
    ACTIONS(60), 1,
      anon_sym_Encryptedindex_COLON,
    STATE(7), 5,
      sym_citation_title,
      sym_citation_text,
      sym_citation_index,
      sym_newline,
      aux_sym_citation_entry_repeat1,
    ACTIONS(54), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [123] = 7,
    ACTIONS(64), 1,
      anon_sym_LF,
    ACTIONS(66), 1,
      anon_sym_Name_COLON,
    ACTIONS(68), 1,
      anon_sym_ID_COLON,
    ACTIONS(70), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(48), 1,
      sym_tool_use_content,
    STATE(9), 5,
      sym_tool_name_line,
      sym_tool_id_line,
      sym_tool_parameter,
      sym_newline,
      aux_sym_tool_use_content_repeat1,
    ACTIONS(62), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [158] = 7,
    ACTIONS(64), 1,
      anon_sym_LF,
    ACTIONS(66), 1,
      anon_sym_Name_COLON,
    ACTIONS(68), 1,
      anon_sym_ID_COLON,
    ACTIONS(70), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(46), 1,
      sym_tool_use_content,
    STATE(9), 5,
      sym_tool_name_line,
      sym_tool_id_line,
      sym_tool_parameter,
      sym_newline,
      aux_sym_tool_use_content_repeat1,
    ACTIONS(72), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [193] = 5,
    ACTIONS(56), 1,
      anon_sym_Title_COLON,
    ACTIONS(58), 1,
      anon_sym_Citedtext_COLON,
    ACTIONS(60), 1,
      anon_sym_Encryptedindex_COLON,
    STATE(8), 5,
      sym_citation_title,
      sym_citation_text,
      sym_citation_index,
      sym_newline,
      aux_sym_citation_entry_repeat1,
    ACTIONS(74), 12,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [224] = 6,
    ACTIONS(78), 1,
      anon_sym_LF,
    ACTIONS(81), 1,
      anon_sym_Title_COLON,
    ACTIONS(84), 1,
      anon_sym_Citedtext_COLON,
    ACTIONS(87), 1,
      anon_sym_Encryptedindex_COLON,
    STATE(8), 5,
      sym_citation_title,
      sym_citation_text,
      sym_citation_index,
      sym_newline,
      aux_sym_citation_entry_repeat1,
    ACTIONS(76), 11,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_POUND_POUND_POUND,
  [257] = 6,
    ACTIONS(64), 1,
      anon_sym_LF,
    ACTIONS(66), 1,
      anon_sym_Name_COLON,
    ACTIONS(68), 1,
      anon_sym_ID_COLON,
    ACTIONS(70), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(12), 5,
      sym_tool_name_line,
      sym_tool_id_line,
      sym_tool_parameter,
      sym_newline,
      aux_sym_tool_use_content_repeat1,
    ACTIONS(90), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [289] = 7,
    ACTIONS(94), 1,
      anon_sym_LF,
    ACTIONS(96), 1,
      anon_sym_LTcite_GT,
    ACTIONS(98), 1,
      sym__text,
    STATE(47), 1,
      sym_system_content,
    STATE(51), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
    STATE(17), 3,
      sym_content_line,
      sym_newline,
      aux_sym_content_repeat1,
    ACTIONS(92), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [323] = 7,
    ACTIONS(94), 1,
      anon_sym_LF,
    ACTIONS(96), 1,
      anon_sym_LTcite_GT,
    ACTIONS(98), 1,
      sym__text,
    STATE(43), 1,
      sym_content,
    STATE(51), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
    STATE(18), 3,
      sym_content_line,
      sym_newline,
      aux_sym_content_repeat1,
    ACTIONS(100), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [357] = 6,
    ACTIONS(104), 1,
      anon_sym_LF,
    ACTIONS(107), 1,
      anon_sym_Name_COLON,
    ACTIONS(110), 1,
      anon_sym_ID_COLON,
    ACTIONS(113), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(12), 5,
      sym_tool_name_line,
      sym_tool_id_line,
      sym_tool_parameter,
      sym_newline,
      aux_sym_tool_use_content_repeat1,
    ACTIONS(102), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [389] = 7,
    ACTIONS(94), 1,
      anon_sym_LF,
    ACTIONS(96), 1,
      anon_sym_LTcite_GT,
    ACTIONS(98), 1,
      sym__text,
    STATE(42), 1,
      sym_content,
    STATE(51), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
    STATE(18), 3,
      sym_content_line,
      sym_newline,
      aux_sym_content_repeat1,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [423] = 7,
    ACTIONS(94), 1,
      anon_sym_LF,
    ACTIONS(96), 1,
      anon_sym_LTcite_GT,
    ACTIONS(98), 1,
      sym__text,
    STATE(41), 1,
      sym_content,
    STATE(51), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
    STATE(18), 3,
      sym_content_line,
      sym_newline,
      aux_sym_content_repeat1,
    ACTIONS(118), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [457] = 6,
    ACTIONS(122), 1,
      anon_sym_LF,
    ACTIONS(125), 1,
      anon_sym_LTcite_GT,
    ACTIONS(128), 1,
      sym__text,
    STATE(51), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
    STATE(15), 3,
      sym_content_line,
      sym_newline,
      aux_sym_content_repeat1,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [488] = 6,
    ACTIONS(133), 1,
      anon_sym_LF,
    ACTIONS(135), 1,
      anon_sym_ID_COLON,
    ACTIONS(137), 1,
      sym_tool_block_start,
    STATE(40), 1,
      sym_tool_result_content,
    STATE(20), 4,
      sym_tool_result_id_line,
      sym_tool_result_block,
      sym_newline,
      aux_sym_tool_result_content_repeat1,
    ACTIONS(131), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [519] = 6,
    ACTIONS(94), 1,
      anon_sym_LF,
    ACTIONS(96), 1,
      anon_sym_LTcite_GT,
    ACTIONS(98), 1,
      sym__text,
    STATE(51), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
    STATE(15), 3,
      sym_content_line,
      sym_newline,
      aux_sym_content_repeat1,
    ACTIONS(139), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [550] = 6,
    ACTIONS(94), 1,
      anon_sym_LF,
    ACTIONS(96), 1,
      anon_sym_LTcite_GT,
    ACTIONS(98), 1,
      sym__text,
    STATE(51), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
    STATE(15), 3,
      sym_content_line,
      sym_newline,
      aux_sym_content_repeat1,
    ACTIONS(141), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [581] = 6,
    ACTIONS(133), 1,
      anon_sym_LF,
    ACTIONS(135), 1,
      anon_sym_ID_COLON,
    ACTIONS(137), 1,
      sym_tool_block_start,
    STATE(45), 1,
      sym_tool_result_content,
    STATE(20), 4,
      sym_tool_result_id_line,
      sym_tool_result_block,
      sym_newline,
      aux_sym_tool_result_content_repeat1,
    ACTIONS(143), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [612] = 5,
    ACTIONS(133), 1,
      anon_sym_LF,
    ACTIONS(135), 1,
      anon_sym_ID_COLON,
    ACTIONS(137), 1,
      sym_tool_block_start,
    STATE(22), 4,
      sym_tool_result_id_line,
      sym_tool_result_block,
      sym_newline,
      aux_sym_tool_result_content_repeat1,
    ACTIONS(145), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [640] = 1,
    ACTIONS(147), 17,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_Name_COLON,
      anon_sym_ID_COLON,
      anon_sym_POUND_POUND_POUND,
      anon_sym_Title_COLON,
      anon_sym_Citedtext_COLON,
      anon_sym_Encryptedindex_COLON,
  [660] = 5,
    ACTIONS(151), 1,
      anon_sym_LF,
    ACTIONS(154), 1,
      anon_sym_ID_COLON,
    ACTIONS(157), 1,
      sym_tool_block_start,
    STATE(22), 4,
      sym_tool_result_id_line,
      sym_tool_result_block,
      sym_newline,
      aux_sym_tool_result_content_repeat1,
    ACTIONS(149), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [688] = 5,
    ACTIONS(64), 1,
      anon_sym_LF,
    ACTIONS(162), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(44), 1,
      sym_citations_content,
    STATE(24), 3,
      sym_citation_entry,
      sym_newline,
      aux_sym_citations_content_repeat1,
    ACTIONS(160), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [715] = 4,
    ACTIONS(64), 1,
      anon_sym_LF,
    ACTIONS(162), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(25), 3,
      sym_citation_entry,
      sym_newline,
      aux_sym_citations_content_repeat1,
    ACTIONS(164), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [739] = 4,
    ACTIONS(168), 1,
      anon_sym_LF,
    ACTIONS(171), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(25), 3,
      sym_citation_entry,
      sym_newline,
      aux_sym_citations_content_repeat1,
    ACTIONS(166), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [763] = 1,
    ACTIONS(174), 15,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
      anon_sym_Title_COLON,
      anon_sym_Citedtext_COLON,
      anon_sym_Encryptedindex_COLON,
  [781] = 1,
    ACTIONS(176), 15,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
      anon_sym_Title_COLON,
      anon_sym_Citedtext_COLON,
      anon_sym_Encryptedindex_COLON,
  [799] = 1,
    ACTIONS(178), 15,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
      anon_sym_Title_COLON,
      anon_sym_Citedtext_COLON,
      anon_sym_Encryptedindex_COLON,
  [817] = 1,
    ACTIONS(180), 14,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_Name_COLON,
      anon_sym_ID_COLON,
      anon_sym_POUND_POUND_POUND,
  [834] = 1,
    ACTIONS(182), 14,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_Name_COLON,
      anon_sym_ID_COLON,
      anon_sym_POUND_POUND_POUND,
  [851] = 1,
    ACTIONS(184), 14,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_Name_COLON,
      anon_sym_ID_COLON,
      anon_sym_POUND_POUND_POUND,
  [868] = 1,
    ACTIONS(186), 14,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_Name_COLON,
      anon_sym_ID_COLON,
      anon_sym_POUND_POUND_POUND,
  [885] = 1,
    ACTIONS(188), 14,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_Name_COLON,
      anon_sym_ID_COLON,
      anon_sym_POUND_POUND_POUND,
  [902] = 1,
    ACTIONS(147), 13,
      sym_tool_block_start,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_ID_COLON,
  [918] = 1,
    ACTIONS(190), 13,
      sym__text,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_LTcite_GT,
  [934] = 1,
    ACTIONS(192), 13,
      sym_tool_block_start,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_ID_COLON,
  [950] = 1,
    ACTIONS(147), 13,
      sym__text,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_LTcite_GT,
  [966] = 1,
    ACTIONS(194), 13,
      sym_tool_block_start,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_ID_COLON,
  [982] = 1,
    ACTIONS(196), 13,
      sym_tool_block_start,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
      anon_sym_LF,
      anon_sym_ID_COLON,
  [998] = 1,
    ACTIONS(198), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1011] = 1,
    ACTIONS(200), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1024] = 1,
    ACTIONS(202), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1037] = 1,
    ACTIONS(204), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1050] = 1,
    ACTIONS(206), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1063] = 1,
    ACTIONS(208), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1076] = 1,
    ACTIONS(210), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1089] = 1,
    ACTIONS(212), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1102] = 1,
    ACTIONS(214), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1115] = 1,
    ACTIONS(216), 10,
      ts_builtin_sym_end,
      sym_user_header,
      sym_system_header,
      sym_assistant_header,
      sym_thinking_header,
      sym_tool_use_header,
      sym_tool_result_header,
      sym_server_tool_use_header,
      sym_server_tool_result_header,
      sym_citations_header,
  [1128] = 4,
    ACTIONS(218), 1,
      anon_sym_LF,
    ACTIONS(220), 1,
      anon_sym_LTcite_GT,
    ACTIONS(223), 1,
      sym__text,
    STATE(50), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
  [1142] = 4,
    ACTIONS(96), 1,
      anon_sym_LTcite_GT,
    ACTIONS(226), 1,
      anon_sym_LF,
    ACTIONS(228), 1,
      sym__text,
    STATE(50), 2,
      sym_cite_tag,
      aux_sym_content_line_repeat1,
  [1156] = 4,
    ACTIONS(230), 1,
      anon_sym_LF,
    ACTIONS(233), 1,
      aux_sym_cite_tag_token1,
    ACTIONS(236), 1,
      anon_sym_LT_SLASHcite_GT,
    STATE(52), 1,
      aux_sym_cite_tag_repeat1,
  [1169] = 4,
    ACTIONS(238), 1,
      anon_sym_LF,
    ACTIONS(240), 1,
      aux_sym_cite_tag_token1,
    ACTIONS(242), 1,
      anon_sym_LT_SLASHcite_GT,
    STATE(54), 1,
      aux_sym_cite_tag_repeat1,
  [1182] = 4,
    ACTIONS(244), 1,
      anon_sym_LF,
    ACTIONS(246), 1,
      aux_sym_cite_tag_token1,
    ACTIONS(248), 1,
      anon_sym_LT_SLASHcite_GT,
    STATE(52), 1,
      aux_sym_cite_tag_repeat1,
  [1195] = 1,
    ACTIONS(250), 3,
      sym__text,
      anon_sym_LF,
      anon_sym_LTcite_GT,
  [1201] = 3,
    ACTIONS(252), 1,
      sym_tool_block_end,
    ACTIONS(254), 1,
      sym_tool_block_content,
    STATE(57), 1,
      aux_sym_tool_param_block_repeat1,
  [1211] = 3,
    ACTIONS(256), 1,
      sym_tool_block_end,
    ACTIONS(258), 1,
      sym_tool_block_content,
    STATE(57), 1,
      aux_sym_tool_param_block_repeat1,
  [1221] = 3,
    ACTIONS(261), 1,
      sym_tool_block_end,
    ACTIONS(263), 1,
      sym_tool_block_content,
    STATE(59), 1,
      aux_sym_tool_param_block_repeat1,
  [1231] = 3,
    ACTIONS(254), 1,
      sym_tool_block_content,
    ACTIONS(265), 1,
      sym_tool_block_end,
    STATE(57), 1,
      aux_sym_tool_param_block_repeat1,
  [1241] = 3,
    ACTIONS(267), 1,
      sym_tool_block_end,
    ACTIONS(269), 1,
      sym_tool_block_content,
    STATE(56), 1,
      aux_sym_tool_param_block_repeat1,
  [1251] = 1,
    ACTIONS(271), 3,
      sym__text,
      anon_sym_LF,
      anon_sym_LTcite_GT,
  [1257] = 2,
    ACTIONS(273), 1,
      sym_tool_block_start,
    STATE(29), 1,
      sym_tool_param_block,
  [1264] = 1,
    ACTIONS(275), 1,
      anon_sym_LF,
  [1268] = 1,
    ACTIONS(277), 1,
      anon_sym_LF,
  [1272] = 1,
    ACTIONS(279), 1,
      aux_sym_tool_name_line_token1,
  [1276] = 1,
    ACTIONS(281), 1,
      anon_sym_LF,
  [1280] = 1,
    ACTIONS(283), 1,
      sym_identifier,
  [1284] = 1,
    ACTIONS(285), 1,
      aux_sym_tool_name_line_token1,
  [1288] = 1,
    ACTIONS(287), 1,
      sym_url,
  [1292] = 1,
    ACTIONS(289), 1,
      aux_sym_tool_name_line_token1,
  [1296] = 1,
    ACTIONS(291), 1,
      aux_sym_tool_name_line_token1,
  [1300] = 1,
    ACTIONS(293), 1,
      aux_sym_tool_name_line_token1,
  [1304] = 1,
    ACTIONS(295), 1,
      aux_sym_tool_name_line_token1,
  [1308] = 1,
    ACTIONS(297), 1,
      aux_sym_tool_name_line_token1,
  [1312] = 1,
    ACTIONS(299), 1,
      sym_identifier,
  [1316] = 1,
    ACTIONS(301), 1,
      anon_sym_LF,
  [1320] = 1,
    ACTIONS(303), 1,
      aux_sym_citation_title_token1,
  [1324] = 1,
    ACTIONS(305), 1,
      aux_sym_citation_title_token1,
  [1328] = 1,
    ACTIONS(307), 1,
      aux_sym_citation_title_token1,
  [1332] = 1,
    ACTIONS(309), 1,
      anon_sym_LF,
  [1336] = 1,
    ACTIONS(311), 1,
      anon_sym_LF,
  [1340] = 1,
    ACTIONS(313), 1,
      anon_sym_LF,
  [1344] = 1,
    ACTIONS(315), 1,
      anon_sym_LF,
  [1348] = 1,
    ACTIONS(317), 1,
      sym_identifier,
  [1352] = 1,
    ACTIONS(319), 1,
      sym_identifier,
  [1356] = 1,
    ACTIONS(321), 1,
      anon_sym_LF,
  [1360] = 1,
    ACTIONS(323), 1,
      anon_sym_LF,
  [1364] = 1,
    ACTIONS(325), 1,
      ts_builtin_sym_end,
  [1368] = 1,
    ACTIONS(327), 1,
      aux_sym_tool_name_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 158,
  [SMALL_STATE(7)] = 193,
  [SMALL_STATE(8)] = 224,
  [SMALL_STATE(9)] = 257,
  [SMALL_STATE(10)] = 289,
  [SMALL_STATE(11)] = 323,
  [SMALL_STATE(12)] = 357,
  [SMALL_STATE(13)] = 389,
  [SMALL_STATE(14)] = 423,
  [SMALL_STATE(15)] = 457,
  [SMALL_STATE(16)] = 488,
  [SMALL_STATE(17)] = 519,
  [SMALL_STATE(18)] = 550,
  [SMALL_STATE(19)] = 581,
  [SMALL_STATE(20)] = 612,
  [SMALL_STATE(21)] = 640,
  [SMALL_STATE(22)] = 660,
  [SMALL_STATE(23)] = 688,
  [SMALL_STATE(24)] = 715,
  [SMALL_STATE(25)] = 739,
  [SMALL_STATE(26)] = 763,
  [SMALL_STATE(27)] = 781,
  [SMALL_STATE(28)] = 799,
  [SMALL_STATE(29)] = 817,
  [SMALL_STATE(30)] = 834,
  [SMALL_STATE(31)] = 851,
  [SMALL_STATE(32)] = 868,
  [SMALL_STATE(33)] = 885,
  [SMALL_STATE(34)] = 902,
  [SMALL_STATE(35)] = 918,
  [SMALL_STATE(36)] = 934,
  [SMALL_STATE(37)] = 950,
  [SMALL_STATE(38)] = 966,
  [SMALL_STATE(39)] = 982,
  [SMALL_STATE(40)] = 998,
  [SMALL_STATE(41)] = 1011,
  [SMALL_STATE(42)] = 1024,
  [SMALL_STATE(43)] = 1037,
  [SMALL_STATE(44)] = 1050,
  [SMALL_STATE(45)] = 1063,
  [SMALL_STATE(46)] = 1076,
  [SMALL_STATE(47)] = 1089,
  [SMALL_STATE(48)] = 1102,
  [SMALL_STATE(49)] = 1115,
  [SMALL_STATE(50)] = 1128,
  [SMALL_STATE(51)] = 1142,
  [SMALL_STATE(52)] = 1156,
  [SMALL_STATE(53)] = 1169,
  [SMALL_STATE(54)] = 1182,
  [SMALL_STATE(55)] = 1195,
  [SMALL_STATE(56)] = 1201,
  [SMALL_STATE(57)] = 1211,
  [SMALL_STATE(58)] = 1221,
  [SMALL_STATE(59)] = 1231,
  [SMALL_STATE(60)] = 1241,
  [SMALL_STATE(61)] = 1251,
  [SMALL_STATE(62)] = 1257,
  [SMALL_STATE(63)] = 1264,
  [SMALL_STATE(64)] = 1268,
  [SMALL_STATE(65)] = 1272,
  [SMALL_STATE(66)] = 1276,
  [SMALL_STATE(67)] = 1280,
  [SMALL_STATE(68)] = 1284,
  [SMALL_STATE(69)] = 1288,
  [SMALL_STATE(70)] = 1292,
  [SMALL_STATE(71)] = 1296,
  [SMALL_STATE(72)] = 1300,
  [SMALL_STATE(73)] = 1304,
  [SMALL_STATE(74)] = 1308,
  [SMALL_STATE(75)] = 1312,
  [SMALL_STATE(76)] = 1316,
  [SMALL_STATE(77)] = 1320,
  [SMALL_STATE(78)] = 1324,
  [SMALL_STATE(79)] = 1328,
  [SMALL_STATE(80)] = 1332,
  [SMALL_STATE(81)] = 1336,
  [SMALL_STATE(82)] = 1340,
  [SMALL_STATE(83)] = 1344,
  [SMALL_STATE(84)] = 1348,
  [SMALL_STATE(85)] = 1352,
  [SMALL_STATE(86)] = 1356,
  [SMALL_STATE(87)] = 1360,
  [SMALL_STATE(88)] = 1364,
  [SMALL_STATE(89)] = 1368,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citation_entry, 5, 0, 4),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_use_section, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_server_tool_use_section, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citation_entry, 6, 0, 4),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_citation_entry_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_citation_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_citation_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_citation_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_citation_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_use_content, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_section, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_section, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tool_use_content_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_use_content_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_use_content_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_use_content_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_use_content_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_thinking_section, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assistant_section, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_server_tool_result_section, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_content, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_section, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_content, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tool_result_content_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_result_content_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_result_content_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_result_content_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citations_section, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citations_content, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_citations_content_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_citations_content_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_citations_content_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citation_title, 4, 0, 6),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citation_text, 4, 0, 7),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citation_index, 4, 0, 8),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_parameter, 6, 0, 5),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_name_line, 4, 0, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_param_block, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_id_line, 4, 0, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_param_block, 3, 0, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_block, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_id_line, 4, 0, 3),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_block, 3, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_server_tool_result_section, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assistant_section, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_thinking_section, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_section, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citations_section, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_section, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_server_tool_use_section, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_section, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_use_section, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [230] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cite_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [233] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cite_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cite_tag_repeat1, 2, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cite_tag, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tool_param_block_repeat1, 2, 0, 0),
  [258] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_param_block_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cite_tag, 3, 0, 1),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [325] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_tool_block_start = 0,
  ts_external_token_tool_block_end = 1,
  ts_external_token_tool_block_content = 2,
  ts_external_token__text = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_tool_block_start] = sym_tool_block_start,
  [ts_external_token_tool_block_end] = sym_tool_block_end,
  [ts_external_token_tool_block_content] = sym_tool_block_content,
  [ts_external_token__text] = sym__text,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_tool_block_start] = true,
    [ts_external_token_tool_block_end] = true,
    [ts_external_token_tool_block_content] = true,
    [ts_external_token__text] = true,
  },
  [2] = {
    [ts_external_token__text] = true,
  },
  [3] = {
    [ts_external_token_tool_block_start] = true,
  },
  [4] = {
    [ts_external_token_tool_block_end] = true,
    [ts_external_token_tool_block_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_greger_external_scanner_create(void);
void tree_sitter_greger_external_scanner_destroy(void *);
bool tree_sitter_greger_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_greger_external_scanner_serialize(void *, char *);
void tree_sitter_greger_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_greger(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_greger_external_scanner_create,
      tree_sitter_greger_external_scanner_destroy,
      tree_sitter_greger_external_scanner_scan,
      tree_sitter_greger_external_scanner_serialize,
      tree_sitter_greger_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
